<a href="https://colab.research.google.com/github/mariahirit/MyFirstProjectBig-Data/blob/master/MyFirstProjectBigData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv("classification_5000.csv")
df.head()

           DateTime  In_Flow  In_Angle  ...  Col_density  Oxygen  Quality_type
0  2021-01-01 00:00     1.41      0.40  ...        -1.40    0.42       Premium
1  2021-01-01 01:00    -1.41     -0.02  ...         0.42   -0.10       Premium
2  2021-01-01 02:00     0.29      0.67  ...         1.48    1.11      Rejected
3  2021-01-01 03:00     2.98      1.00  ...        -2.03   -1.34      Rejected
4  2021-01-01 04:00     0.27      1.92  ...        -1.05   -1.17       Premium

[5 rows x 17 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DateTime       5000 non-null   object
 1   In_Flow        5000 non-null   float64
 2   In_Angle       5000 non-null   float64
 3   In_Temp        5000 non-null   float64
 4   Out_Temp       5000 non-null   float64
 5   In_Pressure    5000 non-null   float64
 6   Viscosity      5000 non-null   float64
 7   Humidity       5000 non-null   float64
 8   Rot_Speed      5000 non-null   float64
 9   Valve_Opening  5000 non-null   float64
 10  Tank_%         5000 non-null   float64
 11  Out_Speed      5000 non-null   float64
 12  Thickness      5000 non-null   float64
 13  Vibration      5000 non-null   float64
 14  Col_density    5000 non-null   float64
 15  Oxygen         5000 non-null   float64
 16  Quality_type   5000 non-null   object
dtypes: float64(15), object(2)
memory usage: 664.2+ KB

In [ ]:
df.corr()

                In_Flow  In_Angle   In_Temp  ...  Vibration  Col_density    Oxygen
In_Flow        1.000000 -0.003215 -0.013636  ...  -0.006062    -0.038673 -0.000930
In_Angle      -0.003215  1.000000 -0.021197  ...  -0.023547     0.021942 -0.003048
In_Temp       -0.013636 -0.021197  1.000000  ...  -0.002501     0.013037 -0.000689
Out_Temp       0.052537 -0.011058  0.017025  ...  -0.010388    -0.034745 -0.015645
In_Pressure    0.225834  0.020030 -0.005671  ...   0.014644    -0.352036  0.009033
Viscosity     -0.005518  0.011512 -0.004853  ...  -0.007153    -0.016358 -0.007108
Humidity       0.577518  0.012110 -0.018469  ...   0.005821    -0.002687  0.034456
Rot_Speed      0.563143 -0.020147  0.008818  ...  -0.015282    -0.166462 -0.034626
Valve_Opening -0.020819 -0.013598 -0.020885  ...   0.013938    -0.002074 -0.012193
Tank_%        -0.107559  0.004809 -0.012042  ...   0.006652    -0.066817  0.040016
Out_Speed      0.005053  0.004233 -0.002168  ...  -0.008690     0.005061  0.003664
Thickness     -0.022900  0.015907  0.012368  ...  -0.024009     0.006112 -0.018229
Vibration     -0.006062 -0.023547 -0.002501  ...   1.000000    -0.003732 -0.022625
Col_density   -0.038673  0.021942  0.013037  ...  -0.003732     1.000000 -0.000561
Oxygen        -0.000930 -0.003048 -0.000689  ...  -0.022625    -0.000561  1.000000

[15 rows x 15 columns]

In [ ]:
df.columns

Index(['DateTime', 'In_Flow', 'In_Angle', 'In_Temp', 'Out_Temp', 'In_Pressure',
       'Viscosity', 'Humidity', 'Rot_Speed', 'Valve_Opening', 'Tank_%',
       'Out_Speed', 'Thickness', 'Vibration', 'Col_density', 'Oxygen',
       'Quality_type'],
      dtype='object')

In [ ]:
orders=df.Col_density.value_counts().count()
orders

835

In [ ]:
df.iloc[2:]

              DateTime  In_Flow  In_Angle  ...  Col_density  Oxygen  Quality_type
2     2021-01-01 02:00     0.29      0.67  ...         1.48    1.11      Rejected
3     2021-01-01 03:00     2.98      1.00  ...        -2.03   -1.34      Rejected
4     2021-01-01 04:00     0.27      1.92  ...        -1.05   -1.17       Premium
5     2021-01-01 05:00     1.75     -0.50  ...        -0.55    0.10       Premium
6     2021-01-01 06:00    -2.89     -0.11  ...         1.76    0.41       Premium
...                ...      ...       ...  ...          ...     ...           ...
4995  2021-07-27 03:00     0.22     -0.42  ...        -2.06   -1.37       Premium
4996  2021-07-27 04:00     0.87     -1.54  ...         1.36   -0.86       Premium
4997  2021-07-27 05:00     0.17     -0.75  ...         0.94   -0.72      Approved
4998  2021-07-27 06:00     0.73      0.40  ...         3.36    0.76      Rejected
4999  2021-07-27 07:00    -0.05     -0.73  ...         0.93    1.60      Approved

[4998 rows x 17 columns]

In [ ]:
df.iloc[2:, :]

In [ ]:
df.dropna()

In [ ]:
df.groupby(by=['Humidity'])

In [ ]:
df.isnull().sum()

In [ ]:
df.notnull().sum()

DateTime         5000
In_Flow          5000
In_Angle         5000
In_Temp          5000
Out_Temp         5000
In_Pressure      5000
Viscosity        5000
Humidity         5000
Rot_Speed        5000
Valve_Opening    5000
Tank_%           5000
Out_Speed        5000
Thickness        5000
Vibration        5000
Col_density      5000
Oxygen           5000
Quality_type     5000
dtype: int64